server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: audit-service
          uri: lb://AUDIT-SERVICE
          predicates:
            - Path=/audit/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/customers/**
          filters:
            - RewritePath=/customers/(?<segment>.*), /api/v1/customers/$\{segment}